version: "3.7"

volumes:
  sveltegobackendevolume:
    name: sveltegobackende-volume

networks:
  sveltegobackendenetwork:
    name: sveltegobackende-network

services:
  pg:
    image: postgres:12.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - sveltegobackendevolume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - sveltegobackendenetwork
  sveltegobackende_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - sveltegobackendenetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
